### ISSUE TITLE
Загрузка данных из Kafka в Clickhouse

### ISSUE THREAD

**Issue by Berupor** [Berupor/UGC-Sprint-1#6]
В рамках этой задачи необходимо обратить внимание на несколько важных моментов:

1. Проверьте, что схема данных вашего аналитического хранилища поддерживает возможность находить самые просматриваемые фильмы и понимать, какие фильмы не досматривают до конца.

2. Продумайте возможность непрерывной работы ETL-процесса так, чтобы он был толерантен к сбоям источника данных и хранилища.

3. Так как поток данных ожидается непрерывным нужно проверить, что ваше приложение не «течёт». То есть нужно внедрить средства мониторинга памяти приложения.

**Comment by NikitaTheGeneral** [comment]
1. Готово
2. Готово
3. Предлагаю пока отложить.
